### ISSUE TITLE
Installation Failure on BG1EE with Song and Silence Chorister Kit Installed 

### ISSUE THREAD

**Issue by jgjensen** [TotoR115/Divine_Remix#5]
How to reproduce: Attempt to install the Cleric Remix component on a BG1EE-only game with the Chorister Kit from Song & Silence installed.  

The installation fails because Weidu tries to find the Nalla.CRE file per instructions in the TP2 file.  That CRE file does not exist in BG1 and so the installation errors out and fails.  Note that this error likely would not happen in a BG2EE or EET installation - the error only occurs in BG1EE.  

I am not tech-savvy enough to write a fix myself, but when I looked at the relevant section of the TP2, I don't see any language that clarifies that Weidu should only look for a Nalla.CRE file in a BG2EE or EET installation, and I suspect that is what needs a fix.

**Comment by TotoR115** [comment]
Should be solved in [49d1d6c](https://github.com/TotoR115/Divine_Remix/commit/49d1d6cab372a1f0ed49aeac47f4033b7d56214e)

@jgjensen Could you try?

**Comment by TotoR115** [comment]
Solve
